# Generated by Django 4.1.7 on 2023-10-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="stock",),
    ]
