# Generated by Django 4.2.6 on 2023-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_unique_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="reviewer_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
