# Generated by Django 4.2.6 on 2023-11-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_customer_zip_code_alter_transaction_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction", name="date_ordered", field=models.DateTimeField(),
        ),
    ]
