# Generated by Django 4.2.6 on 2023-11-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_customer_reviewer_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="name",),
        migrations.AddField(
            model_name="product",
            name="asin",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
