# Generated by Django 4.2.6 on 2023-11-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_transaction_date_ordered"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="description",),
        migrations.RemoveField(model_name="product", name="description",),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[("Married", "Married"), ("Single", "Single")],
                max_length=10,
                null=True,
            ),
        ),
    ]
