# Generated by Django 4.2.6 on 2023-11-03 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_order_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='order',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(default=1432, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='app.transaction'),
            preserve_default=False,
        ),
    ]
