# Generated by Django 4.2.6 on 2023-11-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_transaction_city_transaction_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
