# Generated by Django 4.2.6 on 2023-11-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_product_name_product_asin"),
        ("app", "0008_transaction_zipcode"),
    ]

    operations = []
