# Generated by Django 4.2.6 on 2023-11-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_image_alter_cartitem_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
