# Generated by Django 4.2.6 on 2023-11-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_inventory_review_remove_transaction_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='st_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
