# Generated by Django 4.2.6 on 2023-11-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_inventory_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewText",
            field=models.TextField(blank=True, null=True),
        ),
    ]
